aria2 auto file renaming false
pystardust/ani-cli pull request #1008
Opened 2023-01-31 19:43 UTC by candrapersada

# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-r` range selection works
- [ ] `--dub` both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

2023-01-31 20:28 UTC, port19x commented
Please explain the motivations for turning this option off by default

2023-01-31 23:04 UTC, candrapersada commented
in order to continue a failed download without restarting the download from the beginning with The new file name has a dot and a number(1..9999) appended after the name.

2023-02-01 10:06 UTC, port19x commented
In that case, the -c flag may be more appropriate.
-c continues the file download for partially downloaded files.
-c doesn't change behaviour of fresh downloads either.

2023-02-01 12:40 UTC, port19x requested changes

2023-02-01 12:40 UTC, port19x commented on ani-cli
> +	*) aria2c --check-certificate=false --auto-file-renaming=false --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide ;;
```suggestion
	*) aria2c --check-certificate=false --continue --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide ;;
```

2023-02-01 12:45 UTC, port19x approved these changes

2023-02-01 12:45 UTC, merged

2023-02-01 12:58 UTC, candrapersada commented
![image](https://user-images.githubusercontent.com/36833664/216049468-eb0b1133-0ba0-48d8-9ac3-de27b19b04f0.png)