search field changed into while loop
pystardust/ani-cli pull request #1020
Opened 2023-02-05 11:42 UTC by r4vanan

i don't want to turn back after entering into ani-cli tool so i done this. if you like too then pull it else leave it thanks

2023-02-05 11:50 UTC, port19x commented
It doesn't quite behave as expected but I agree with that UX

2023-02-06 07:58 UTC, Derisis13 requested changes
Lots of repeated lines, there should be a way to solve it without that.

2023-02-06 07:58 UTC, Derisis13 commented on ani-cli
> +			clear
Why clear here?

2023-02-06 07:58 UTC, Derisis13 commented on ani-cli
> +		clear
There is an escape sequence that sets the cursor to the previous line and deletes it. Use that, not clear.

2023-02-06 07:58 UTC, Derisis13 commented on ani-cli
> +		search_anime "$query"
The regex for replacing spaces is missing from here

2023-02-06 10:28 UTC, closed without merging