search field changed into while loop
pystardust/ani-cli pull request #1023
Opened 2023-02-06 10:46 UTC by r4vanan

i don't want kill that process while for searching the anime so i made a while loop for that.

2023-02-06 13:35 UTC, 71zenith commented
appease the linter

2023-02-06 13:44 UTC, r4vanan commented
> appease the linter

I can't understand what you mean sir

2023-02-07 02:40 UTC, r4vanan commented
I think now it's ok

2023-02-07 09:58 UTC, RaynardGerraldo commented
searching for anime as argument doesnt work with this, ./ani-cli naruto just prompts me to search anime again

2023-02-07 09:59 UTC, port19x requested changes

2023-02-07 09:59 UTC, port19x commented on ani-cli
> +	search_loop
this would break external menu compatibility

2023-02-07 11:40 UTC, r4vanan commented
i think now `./ani-cli naruto` it can possible

2023-02-07 15:14 UTC, r4vanan commented
now it can work with rofi

2023-02-07 15:59 UTC, RaynardGerraldo commented
> i don't want kill that process while for searching the anime so i made a while loop for that.

can you explain what exactly this means and what it improves? because I dont see a difference, you can show some screenshots

2023-02-07 16:40 UTC, r4vanan commented
if i search the anime name. if the result is not found means it kill the process i dont like that process. so i changed that and do the loop thing. like if you enter the wrong or invalid name it will ask the name again. it will work in rofi too. no matter how many time you entered wrong name. if the result not found means it will ask the name again

2023-02-07 17:02 UTC, RaynardGerraldo commented
> if i search the anime name. if the result is not found means it kill the process i dont like that process. so i changed that and do the loop thing. like if you enter the wrong or invalid name it will ask the name again. it will work in rofi too. no matter how many time you entered wrong name. if the result not found means it will ask the name again

ok, got it

2023-02-08 14:47 UTC, port19x commented
This is straightup poorly implemented. Not sure if you can refactor it, or if it needs to be this branchy in order to work

2023-02-08 14:54 UTC, r4vanan commented
You can close it. Because I like this thing so I modified like this

2023-02-08 15:21 UTC, closed without merging