fix: some m3u8 downloads were broken
pystardust/ani-cli pull request #1109
Opened 2023-05-05 13:18 UTC by Yashpal2004

## Type of change

- [x] Bug fix

## Description

m3u8-Download-Fixed #1108

2023-05-05 20:41 UTC, port19x requested changes
bump version

2023-05-05 20:41 UTC, port19x commented on ani-cli
> +
```suggestion
```

2023-05-05 20:41 UTC, port19x commented on ani-cli
> +# Downloads a file from a URL and saves it with the specified filename in the specified directory
```suggestion
```

2023-05-05 20:44 UTC, port19x commented
Can confirm this fixes the issue

2023-05-06 01:38 UTC, RubenPonce commented on ani-cli
> +    fi
What if the url is not an m3u8 or is very large? 
Wouldn't want it to curl an entire mp4 so there should be a timeout.
```suggestion
    case $1 in
        *m3u8*) ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4" ;;
        *) if curl -s -m 5 "$1" | grep -q '^#EXTM3U'; then
        ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4"
    else
        aria2c --check-certificate=false --continue --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide
  fi ;;
    esac
```

2023-05-06 02:42 UTC, Yashpal2004 commented
> bump version

How to do that?
I am actually new. to GIT.

2023-05-06 07:07 UTC, port19x commented on ani-cli
> +  fi ;;
This is pretty bad.
First you request with curl, then again with ffmpeg...

2023-05-06 08:49 UTC, port19x commented
> 

Change the variable on the third line in ani-cli

2023-05-08 09:22 UTC, port19x approved these changes

2023-05-08 09:22 UTC, merged