Disable loading aria2.conf file.
pystardust/ani-cli pull request #1135
Opened 2023-05-27 05:29 UTC by candrapersada

Disable loading aria2.conf file. to Disable `enable-rpc=true` from `${HOME}/.aria2/aria2.aria2.conf`

# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-S` select index works
- [ ] `-r` range selection works
- [ ] `--dub` and regular (sub) mode both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

2023-05-27 09:11 UTC, port19x requested changes
Please also elaborate on why rpc should be disabled

2023-05-27 09:11 UTC, port19x commented on ani-cli
> +                aria2c --no-conf=true --check-certificate=false --continue --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide
```suggestion
                aria2c --enable-rpc=false --check-certificate=false --continue --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide
```

2023-05-27 09:38 UTC, candrapersada commented
> Please also elaborate on why rpc should be disabled

because when using `enable-rpc=true` in `aria2.conf` you can't use `aria2c <URI>`

2023-05-27 11:02 UTC, port19x commented
bump the version

2023-05-28 07:06 UTC, port19x approved these changes

2023-05-28 07:06 UTC, merged