added the '--save-position-on-quit' to continue from where the user h…
pystardust/ani-cli pull request #1154
Opened 2023-06-17 14:46 UTC by c2700

…ad left off on said episode

# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-S` select index works
- [ ] `-r` range selection works
- [ ] `--dub` and regular (sub) mode both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

2023-06-17 19:14 UTC, Derisis13 requested changes
If only it was this easy. But the different providers' links are treated as separate media, so if you get a different one the next time, it won't work. And the links don't live forever, which means that once they expire it'll be a separate media, won't work as intended.

Also there's the ambiguity of whether you just want to skip the end credits or you couldn't finish the episode in your lunch break. 

All of this can be probably resolved, but it needs some thinking

2023-06-18 05:51 UTC, justchokingaround commented
mpv has a keybind by default to do this, you can press shift+q instead of just q to quit. you can also set the option to save on quit by default in your mpv.conf

2023-06-18 05:51 UTC, closed without merging

2023-06-18 13:08 UTC, c2700 commented
> mpv has a keybind by default to do this, you can press shift+q instead of just q to quit. you can also set the option to save on quit by default in your mpv.conf

Learned something new today :)

2023-06-18 13:32 UTC, c2700 commented
> If only it was this easy. But the different providers' links are treated as separate media, so if you get a different one the next time, it won't work. And the links don't live forever, which means that once they expire it'll be a separate media, won't work as intended.
> 
> Also there's the ambiguity of whether you just want to skip the end credits or you couldn't finish the episode in your lunch break.
> 
> All of this can be probably resolved, but it needs some thinking

My bad. I opened this PR cuz it worked for as intended on all the episodes that I have been watching & have watched & skipping the outri & intro was something that didn't cross my mind. But to skip the outro & intro is it possible for sponsorblock to be used here? Sure the sponsorblock database may need to be updated every now & then but to reduce the work all the info of all available intros & outros could be scraped from vimeo, youtube or dailymotion & that could be put into the sponsorblock's database which will be applied to all the episodes that have the same intro & outro. This is just one way I could come up with skipping segements cuz I did see mpv being shown as a 3rd party port in the sponsorblock's site

2023-06-18 16:47 UTC, justchokingaround commented
@c2700 
- there is already an mpv extension to do that: https://github.com/rui-ddc/skip-intro (it's set to the TAB keybind by default, but you can change that). there is also a sponsorblock extension, but that's for youtube, not for anime. skip-intro has never failed me once for anime in ~1.5 years of using it (if u're interested in this, u can check my mpv config: https://github.com/justchokingaround/dotfiles/tree/main/mpv)
- the reason why your code in the pr worked in your testing, is because the links don't expire immediately, so you got lucky, but it is not a feasible approach in general
- the feature that you want, where the progress is saved to the exact second, can be implemented through mpv's socket and socat, here is an example of how that can be done: https://github.com/justchokingaround/lobster/blob/main/lobster.sh#L400-L417
however this feature seems kinda like bloat in ani-cli's case, and it would require rewriting the history implementation + an additional dependency

2023-06-18 17:56 UTC, c2700 commented
will check them all out. thank you again :)

2023-06-18 21:07 UTC, justchokingaround commented
this part would require a rewrite: https://github.com/pystardust/ani-cli/blob/master/ani-cli#L220-L234, this part too: https://github.com/pystardust/ani-cli/blob/master/ani-cli#L398-L412, the play function would require many additional checks, and it would add many lines of code, especially since there is a need for an implementation with socat and without it, since it would be an optional dependency

2023-06-18 21:34 UTC, c2700 commented
okay, now that you've pointed me over there I see how much of a change it will need. mind if I implement the changes? (As long as the position tracker alone isn't bloat in ani-cli's case i.e.)

2023-06-19 04:13 UTC, justchokingaround commented
you can implement it if ubwish, but it's unlikely that we will merge it into ani-cli. socat must be an optional dependency, because it doesn't exist on windows, so u must also have coverage for the case where u just play videos, without using socat and saving position

2023-06-19 10:33 UTC, c2700 commented
okay, will implementing the necessary changes then

2023-06-19 10:34 UTC, justchokingaround commented
what?

2023-06-19 16:14 UTC, c2700 commented
As in, I'll be making the changes necessary to implement the "start from where I left off" if you're okay with it

2023-06-19 16:21 UTC, justchokingaround commented
sure, u can hmu if u got any questions or need help. i'm personally in favor of this feature, but i dont think thats the case for all maintainers

2023-06-19 17:41 UTC, c2700 commented
sure, will do :)