docs: hacking guide & flowchart
pystardust/ani-cli pull request #1188
Opened 2023-08-02 20:46 UTC by Derisis13

# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [x] Documentation update

## Description

Medium-sized writeup about how to modify ani-cli for sites with similar structure.
No code was modified.

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-S` select index works
- [ ] `-r` range selection works
- [ ] `--dub` and regular (sub) mode both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

2023-08-02 20:56 UTC, Derisis13 commented
lol svg is text format after all, so it works really well with git... I didn't write a 771 line documentation (but maybe I should bump it 6 lines?)

2023-08-04 08:09 UTC, port19x requested changes
Please use a rendered, non-transparent png or jpg image to embed into hacking.md

As is, the flowchart is barely visible in githubs dark mode

2023-08-04 08:15 UTC, port19x commented on hacking.md
> +- understanding of http(s) requests and proficiency with curl
```suggestion
- understanding of http(s) requests
```

2023-08-04 11:01 UTC, justchokingaround commented on hacking.md
> +As a nuclear option you can resort to [Burp Suite](https://portswigger.net/burp/communitydownload).
this is not beginner friendly, and unnecessarily complicated imo

2023-08-04 11:04 UTC, justchokingaround commented
i've been thinking of writing a shellscript webscraping guide as a separate repo. what would be better, incorporating a lot of new information into this ani-cli guide, or having a more detailed guide in a separate repo, and have this guide only mention which things should be changed in the ani-cli script specifically?
i'll probably also add an example for a new provider implementation

2023-08-04 11:11 UTC, justchokingaround commented
we should also mention the existence of debug mode in `sh`, since that would make the troubleshooting process much easier, rather than seeing error messages such as `Episode not found`

2023-08-04 11:43 UTC, port19x commented
> we should also mention the existence of debug mode in `sh`, since that would make the troubleshooting process much easier, rather than seeing error messages such as `Episode not found`

Yeah, `sh -x` is big

2023-08-04 14:21 UTC, CoolnsX commented
> we should also mention the existence of debug mode in `sh`, since that would make the troubleshooting process much easier, rather than seeing error messages such as `Episode not found`

My french brother is alive

2023-08-06 07:14 UTC, port19x commented
> i've been thinking of writing a shellscript webscraping guide as a separate repo. what would be better, incorporating a lot of new information into this ani-cli guide, or having a more detailed guide in a separate repo, and have this guide only mention which things should be changed in the ani-cli script specifically? i'll probably also add an example for a new provider implementation

There is something like really good in your stars list iirc. I wouldn't bother

2023-08-06 07:15 UTC, port19x approved these changes

2023-08-06 07:41 UTC, justchokingaround commented
blatzar/scraping-tutorial ?

2023-08-06 09:25 UTC, merged