fix: update title in history file
pystardust/ani-cli pull request #1360
Opened 2024-06-03 17:15 UTC by 71zenith

fix: update outdated titles in history selection

# Pull Request Template

## Type of change

- [ ] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

*ramble here*

## Checklist

- [ ] any anime playing
- [ ] bumped version
---
- [ ] next, prev and replay work
- [ ] `-c` history and continue work
- [ ] `-d` downloads work
- [ ] `-s` syncplay works
- [ ] `-q` quality works
- [ ] `-v` vlc works
- [ ] `-e` select episode works
- [ ] `-S` select index works
- [ ] `-r` range selection works
- [ ] `--skip` ani-skip works
- [ ] `--skip-title` ani-skip title argument works
- [ ] `--no-detach` no detach works
- [ ] `--dub` and regular (sub) mode both work
- [ ] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [ ] `-h` help info is up to date
- [ ] Readme is up to date
- [ ] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

2024-06-03 17:16 UTC, 71zenith commented
I've done my preliminary testing however hist file can be widely different from user to user. I'll appreciate more testing

2024-06-04 18:48 UTC, justchokingaround approved these changes

2024-06-06 13:33 UTC, port19x commented
Wow

2024-06-06 13:34 UTC, port19x requested changes
just blocking this so I can test on friday / saturday

2024-06-10 08:54 UTC, port19x approved these changes
I totally forgot to test this.
But since it's a small change I'll just merge as is

2024-06-10 08:54 UTC, merged