Run ani-cli on Mac
pystardust/ani-cli pull request #137
Opened 2021-11-20 14:35 UTC by Cartmanishere

`setsid` is the only reason this doesn't work on Mac. 

If we replace it with `nohup`, it works perfectly on MacOS.

2021-11-20 23:06 UTC, ghyatzo commented
another option would be `($player_fn --http-header-fields="Referer: $embedded_video_url" "$video_url" > /dev/null 2>&1 &)`

2021-12-07 04:46 UTC, fgyamauti commented
Probably stupid. Still, at least for macOS 10.13.6, I had to manually create an empty file /Users/username/.cache/ani-hsts .

2021-12-29 17:24 UTC, ura43 commented
I welcome the replacement of setsid through nohup.
Please resolve the conflicts with current master and I'll merge

2021-12-30 16:36 UTC, ura43 requested changes
Please resolve the current conflicts

2021-12-31 07:39 UTC, merged