fix: remove hostname from uname output in OS detection
pystardust/ani-cli pull request #1440
Opened 2024-10-13 07:56 UTC by VAISHAKH-GK

# fix: remove hostname from uname output in OS detection

## Type of change

- [X] Bug fix
- [ ] Feature
- [ ] Documentation update

## Description

Using $(uname -a | awk '{$2=""; print $0}') instead of just uname -a helps remove the hostname from the output. hostname can vary between systems, which might lead to incorrect OS detection. By stripping out the hostname case statement accurately matches the relevant OS identifiers.

In my system script not work properly because my hostname is "vaishakh" , because it contains "ish" the case identify my linux device as ios device and ani-cli failed to work play the video in mpv/vlc.

## Checklist

- [X] any anime playing
- [X] bumped version
---
- [X] next, prev and replay work
- [X] `-c` history and continue work
- [X] `-d` downloads work
- [X] `-s` syncplay works
- [X] `-q` quality works
- [X] `-v` vlc works
- [X] `-e` select episode works
- [X] `-S` select index works
- [X] `-r` range selection works
- [X] `--skip` ani-skip works
- [X] `--skip-title` ani-skip title argument works
- [X] `--no-detach` no detach works
- [X] `--dub` and regular (sub) mode both work
- [X] all providers return links (not necessarily on a single anime, use debug mode to confirm)
---
- [X] `-h` help info is up to date
- [X] Readme is up to date
- [X] Man page is up to date

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Non-whole episodes: Tensei shitara slime datta ken (ep. 24.5, ep. 24.9)

2024-10-13 17:18 UTC, HirschBerge commented
```
  check-no-awk:
    name: No Awk Allowed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: verify that noone added awk
      run: '! grep awk "./ani-cli"'
   ```
awk is frowned upon. I would probably suggest `cut` something like `uname -a | cut -d ' ' -f 1,3-` at first blush does the job better even than awk since it doesn't leave two spaces in the output

2024-10-17 06:50 UTC, port19x commented
@HirschBerge is exactly right. We have a no awk policy over here

2024-10-17 06:53 UTC, port19x requested changes
See my suggestions for how to get rid of the awk dependency.

Your change itself is well reasoned and a good contribution

2024-10-17 06:53 UTC, port19x commented on ani-cli
> +case "$(uname -a | awk '{$2=""; print $0}')" in
```suggestion
case "$(uname -a | cut -d " " -f 1,3-)" in
```

2024-10-17 06:53 UTC, port19x commented on ani-cli
> +            case "$(uname -a | awk '{$2=""; print $0}')" in
```suggestion
            case "$(uname -a | cut -d " " -f 1,3-)" in
```

2024-10-17 06:55 UTC, VAISHAKH-GK commented
Thanks for the suggestion i will remove awk and will update the pull request

2024-10-17 12:43 UTC, port19x approved these changes
thx for the contrib :crown:

2024-10-17 12:43 UTC, merged

2024-10-17 12:51 UTC, VAISHAKH-GK commented
> thx for the contrib 👑

Happy to be helpful and thanks for the understanding