Support for iina and removal of ampersands
pystardust/ani-cli pull request #256
Opened 2022-01-01 20:23 UTC by tennyson-mccalla

This allowed iina to work for me

2022-01-01 20:26 UTC, tennyson-mccalla commented
Addresses https://github.com/pystardust/ani-cli/issues/254

2022-01-01 21:09 UTC, RaynardGerraldo reviewed
change `ORIGINAL_DIR="/Users/Tennyson/ani-cli"` this part back to 0

2022-01-01 21:11 UTC, RaynardGerraldo commented
oh and also we are going to support more video players but we are not going to match it by making a case for every video player, try removing `"iina")` and change it to `*)` to do a wildcard match and see if it still works

2022-01-01 21:19 UTC, tennyson-mccalla commented
> change `ORIGINAL_DIR="/Users/Tennyson/ani-cli"` this part back to 0

I caught that on diff and the second commit fixed it.

Will try the wildcard thing right now.

2022-01-01 21:53 UTC, tennyson-mccalla commented
Wildcard worked well. Making a new PR.

2022-01-01 22:05 UTC, RaynardGerraldo commented
@tennyson-mccalla since this pr now supports all video players that could play streams,you can change the title to something along those lines

2022-01-01 22:08 UTC, tennyson-mccalla commented
Ok, better name. Thanks for the help here @RaynardGerraldo.

2022-01-02 08:51 UTC, ura43 approved these changes

2022-01-02 08:56 UTC, RaynardGerraldo commented
> Ok, better name. Thanks for the help here @RaynardGerraldo.

to make this even better, you can put this `-o use media player of your own choice : ani-cli -o <media-player>` in help_text()
and add "knuhdHDqo:p:-:v" to https://github.com/pystardust/ani-cli/blob/4a94745829194f187e1d7b820c171a648b68eab0/ani-cli#L386 , then add `o)
			           player_fn=$OPTARG
			          ;;` in https://github.com/pystardust/ani-cli/blob/4a94745829194f187e1d7b820c171a648b68eab0/ani-cli#L387

This way users can specify what video player they want using -o and not change it directly from the code

2022-01-02 12:05 UTC, RaynardGerraldo commented
@ura43 i noticed that you assigned me to this pr, I can implement the changes now but can I wait for @tennyson-mccalla to do it so that he can test it with IINA?

2022-01-02 12:13 UTC, Dink4n commented
Yes, you can

2022-01-02 12:30 UTC, tennyson-mccalla commented
> @ura43 i noticed that you assigned me to this pr, I can implement the changes now but can I wait for @tennyson-mccalla to do it so that he can test it with IINA?

Testing and reporting back later today.

2022-01-02 14:05 UTC, ura43 commented
I assigned you to do the bulk of the reviewing on this PR @RaynardGerraldo 

Just curious, could we just have no case statement at all?
Like have it always use the *) case and just pass mpv as the default for that?

2022-01-02 14:08 UTC, RaynardGerraldo commented
> Just curious, could we just have no case statement at all? Like have it always use the *) case and just pass mpv as the default for that?

I have been thinking about this ,but with that we're removing the -v(vlc option) ,good?

2022-01-02 15:43 UTC, tennyson-mccalla commented
The o option with user choice for player works well with mpv (default) and iina. I'm going to push this commit to my fork and add to the PR.

Also corrected a few minor whitespace issues.

2022-01-02 20:48 UTC, tennyson-mccalla commented
I’ll also do a rewrite with the case statement removed just to test and see how it feels.

2022-01-03 03:01 UTC, tennyson-mccalla commented
> I’ll also do a rewrite with the case statement removed just to test and see how it feels.

I've also done this. It works perfectly well. Someone would just have to handle the rewritten instruction/examples if you want me to push this change up as well.

2022-01-03 15:31 UTC, RaynardGerraldo commented
If we remove the cases for mpv and vlc and just use wildcard with mpv as default,can this feature be in the slimmed down branch? @Dink4n @ura43

2022-01-03 18:04 UTC, tennyson-mccalla commented
> If we remove the cases for mpv and vlc and just use wildcard with mpv as default,can this feature be in the slimmed down version? @Dink4n @ura43

I removed the entire case statement, asterisk included, and it was good. If I had a vote I’d vote for this just for simplicity’s sake.

2022-01-04 03:48 UTC, Dink4n commented
Removing the entire `case` statement won't work anymore. We need to give `referer` to players now.

2022-01-04 09:32 UTC, ura43 commented
> Removing the entire `case` statement won't work anymore. We need to give `referer` to players now.

Since when?
Also, can't we just add the referer before? 
Doesn't sound like a player specific problem

2022-01-04 09:37 UTC, Dink4n commented
Every player has a different option for setting `referers`

E.g:
mpv has `--http-header-fields="Referer: $referer"`
vlc has `--http-referrer="$referer`

2022-01-04 11:22 UTC, tennyson-mccalla commented
I didn’t test with VLC but that’s disappointing to hear it won’t work like MPV and IINA.

2022-01-04 15:06 UTC, ura43 commented
> Every player has a different option for setting `referers`
> 
> E.g: mpv has `--http-header-fields="Referer: $referer"` vlc has `--http-referrer="$referer`

Understandable

2022-01-04 19:06 UTC, ura43 commented
But lets not loose hope, this is a highly desireable feature and we're moving fast

2022-01-14 14:12 UTC, ura43 requested changes
Please bump to latest changes, we may be able to merge this before the end of the month

2022-01-14 18:07 UTC, tennyson-mccalla commented
Got busy once holiday break ended and couldn’t get back to this. Will try.

2022-01-16 17:10 UTC, tennyson-mccalla commented
Should be better now but I can't help but feel that this is still fragile as I don't know many other players will use the "referrer" format that mpv uses. But I can confirm that mpv, vlc, and iina work with this. Please test it out yourself.

2022-01-18 05:17 UTC, ura43 approved these changes

2022-01-18 05:18 UTC, ura43 commented
Tested incompatible with celluloid

2022-01-18 05:22 UTC, ura43 commented
Could you maybe list some players that were tested successful? Because if it's just IINA, I propose we call it -i and actually make it specificly iina

2022-01-18 07:43 UTC, tennyson-mccalla commented
> Could you maybe list some players that were tested successful? Because if it's just IINA, I propose we call it -i and actually make it specificly iina

Right now all I'm testing are MPV, VLC, and IINA. All MPV derivatives should probably work with that default case. I don't have any other players to test with.

This piece was definitely simpler before all of the referrer stuff altered things. I feel like coming up with an alphabet soup to support every player is going to be as bad as a huge case statement that does the same.

2022-01-18 08:01 UTC, tennyson-mccalla commented
> Tested incompatible with celluloid

When did it last have celluloid compatibility?

2022-01-18 11:23 UTC, ura43 commented
> > Tested incompatible with celluloid
> 
> When did it last have celluloid compatibility?

Celluloid is a gtk mpv frontend. Our assumption that caused us supporting iina with a default case was that all, or even most, mpv frontends would share the flags

2022-01-18 11:24 UTC, ura43 commented
I still welcome the change, but in this case I would find a `-i` that calls iina move appealing

2022-01-18 11:59 UTC, tennyson-mccalla commented
> I still welcome the change, but in this case I would find a `-i` that calls iina move appealing

Alright, I’ll make the change. If it gets merged in see if you can figure out what it might take to get celluloid working. I don’t have easy access to a Linux machine right now.

2022-01-19 07:16 UTC, ura43 commented
Tested successfully, so at least it didn't break linux+mpv

2022-01-19 07:16 UTC, ura43 approved these changes

2022-01-19 07:16 UTC, merged

2022-06-06 12:14 UTC, DaBigBlob commented
hello hello hello
https://github.com/pystardust/ani-cli/pull/741
this should fix everything
i went through the iina docs and have fixed everything related to this issue

2022-06-06 15:07 UTC, tennyson-mccalla commented
I'll check this out later today. Thanks for the work.