Add version number
pystardust/ani-cli pull request #349
Opened 2022-01-16 12:15 UTC by 3ricsonn

I added a version number for reference to see which practical version is used in case of a bug, so misconception are more unlikely to accrue

2022-01-16 12:20 UTC, 3ricsonn commented
Would be a suggestion to #348

2022-01-17 13:48 UTC, ura43 requested changes

2022-01-17 13:48 UTC, ura43 commented on ani-cli
> +VERSION="1.0"
Actually please set 1.0.0 since three numbers seem to be best practice here on github

2022-01-17 13:49 UTC, ura43 commented on ani-cli
> +VERSION="1.0"
actually its such a small change I can do that myself

2022-01-17 13:49 UTC, ura43 approved these changes

2022-01-17 13:49 UTC, merged