Update README.md
pystardust/ani-cli pull request #657
Opened 2022-04-16 14:54 UTC by FireTonnor

Added mov-cli

2022-04-16 16:53 UTC, port19x requested changes

2022-04-16 16:53 UTC, port19x commented on README.md
> +- [Others]
The others section should be at the bottom of the table of contents, but above contribution guidelines

2022-04-16 16:53 UTC, port19x commented on README.md
> +   -[mov-cli](https://github.com/mov-cli/mov-cli)
This should include much more of our neighbourhood.
A few to consider:
https://github.com/iamchokerman/ani-sync
https://github.com/justfoolingaround/animdl
https://github.com/saikou-app/saikou
https://github.com/sdaqo/anipy-cli
https://github.com/CoolnsX/dra-cla
https://github.com/Soviena/kaa.si-cli
https://github.com/MangDL/MangDL

2022-04-16 16:53 UTC, port19x commented
I'm generally very sceptical, I think chokerman can better judge if this should be a thing

2022-04-16 18:43 UTC, iamchokerman commented
i am in favor of this, however as port said it should be at the bottom of the table of contents, but above contribution guidelines, and you need to make the formatting look more presentable

https://github.com/7USTIN/manga-cli

2022-04-16 18:46 UTC, FireTonnor commented
Ok I will edit it we I get home

2022-04-16 20:46 UTC, iamchokerman approved these changes

2022-04-17 06:18 UTC, port19x approved these changes

2022-04-17 06:18 UTC, merged