feat: ani-sync on windows
pystardust/ani-cli pull request #700
Opened 2022-04-30 19:04 UTC by iamchokerman

# Pull Request Template

## Type of change

- [ ] Bug fix
- [X] Feature
- [ ] Documentation update

## Description

Tested with a Windows User, works as expected

## Checklist

- [X] any anime playing
- [X] bumped version
- [X] next, prev and replay work
- [X] quality works
- [X] downloads work
- [X] quality works with downloads
- [X] select episode -a and rapid resume work
- [X] syncplay -s works
- [X] autoplay, aka range selection, works

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Not uploaded: one piece dub episode 590
- Unreleased: soredemo ayumu wa yosetekuru
- Short id (for decryption): Log Horizon episode 1-2

2022-04-30 21:17 UTC, Derisis13 commented on ani-cli
> +		-s watch anime together with friends, using Syncplay (works with mpv only)
Ehm

2022-04-30 21:22 UTC, Derisis13 requested changes
This shall make a nice release once complete

2022-04-30 21:22 UTC, Derisis13 commented on ani-cli
> +				*Msys) player_fn="/c/Program Files (x86)/Syncplay/Syncplay.exe" ;;
These can be consolidated to one line, tags separated with a `|`

2022-04-30 21:22 UTC, Derisis13 commented on ani-cli
> +		-s watch anime together with friends, using Syncplay (works with mpv only)
(Probably some whitespace error here, can't see it clear since on mobile)

2022-05-01 13:20 UTC, port19x commented
> This shall make a nice release once complete

definitely

2022-05-02 10:39 UTC, Derisis13 approved these changes
I don't have anyone to watch together though...

2022-05-03 08:50 UTC, port19x commented
I'd like to merge 707 first and then release this

2022-05-03 09:19 UTC, iamchokerman commented
sounds good

2022-05-04 08:47 UTC, port19x commented on README.md
> +A cli to browse and watch anime (alone AND with friends). This tool scrapes the site <a href="https://gogoplay5.com">gogoplay.</a>
Very big brain marketing, I like it

2022-05-04 08:58 UTC, iamchokerman commented on README.md
> +A cli to browse and watch anime (alone AND with friends). This tool scrapes the site <a href="https://gogoplay5.com">gogoplay.</a>
:)

2022-05-04 10:24 UTC, port19x commented
Release checklist

- [ ] Matrix and Revolt links (in #707)
- [ ] Repology badge (in #707)
- [ ] #707 merged
- [ ] Fix long access time (issue #709)
- [ ] Update Termux instructions to advise usage of native package

2022-05-05 12:51 UTC, port19x commented
We're very close to release. If possible I'd like to merge this this evening

2022-05-05 20:20 UTC, port19x commented
> ~Wait wait.. we don't hv native package on termux yet..~ ~I also read all those link u send but right now it's not in standard repos..~ I checked it now and installed it.. but it's installing the standard mpv... Not the custom one we wrote in our documentation Also it's an older version.. like 2.1.0 and not working..

Which is why I currently have an open PR at the termux-packages repo...

2022-05-05 20:24 UTC, merged

2022-05-05 21:00 UTC, port19x commented
I just want to see if termux native package is viable under ideal conditions