Add custom UI support and dmenu UI
pystardust/ani-cli pull request #801
Opened 2022-06-26 20:39 UTC by rakusan2

## Type of change

- [ ] Bug fix
- [x] Feature
- [ ] Documentation update

## Description

With the UI section being in a separate file, it is easy to apply additional UI's over it.
This adds an option for that along with a custom UI to make use of it

This extra UI is for `dmenu`
With this: 
- `dmenu` handles the selection menu.
- it also takes the prompt input which is then split into `REPLY` and `REPLY2` same as what `read` does
- selection menu is shown only after the player closes
- input is still printed to console to not change the look of it

The new UI is used with `ani-cli -u dmenu`

## Checklist

- [x] any anime playing
- [x] bumped version
- [x] next, prev and replay work
- [x] quality works
- [x] downloads work
- [x] quality works with downloads
- [x] select episode -a and rapid resume work
- [x] syncplay -s works
- [x] autoplay, aka range selection, works

## Additional Testcases

- The safe bet: One Piece
- Episode 0: Saenai Heroine no Sodatekata ♭
- Unicode: Saenai Heroine no Sodatekata ♭
- Not uploaded: one piece dub episode 590
- Unreleased: soredemo ayumu wa yosetekuru
- Short id (for decryption): Log Horizon episode 1-2

2022-06-30 09:13 UTC, Derisis13 commented
@rakusan2 I created a wiki page for the UI script, hopefully it is helpful.

2022-07-04 03:15 UTC, rakusan2 commented
My intention was to have this run over the existing UI and only change the prompts. That is why the input gets printed to the console after.
I did not want to copy anything that would not change.

Do prefer for this UI to be completely its own thing instead of reimplementing what differs?

2022-07-08 11:01 UTC, port19x requested changes
No.
I don't think custom UI support is in any way justified.
However a dmenu UI could be useful to some
Maybe you can both support dmenu and rofi?

2022-07-09 04:18 UTC, rakusan2 commented
How would you like for the `dmenu` UI to be turned on or switched with the default UI?
`dmenu` currently does not work under Wayland and therefore needs to be switchable if `UI_dmenu` is to be added

Solutions:
1. Use `-u` option to select the UI
2. Use the ENV variable `ANI_CLI_UI` to select the UI
3. Use a symlink
    - This would entail renaming `UI` to `UI_default` and if `UI` does not exist, linking it to `UI_default`
    - Update would not touch this symlink

Since solution 1 is off the table, what about 2 or 3?

2022-07-21 07:15 UTC, Derisis13 commented
Since the script was re-merged into a single file, external module support is depecated.

2022-07-21 07:15 UTC, closed without merging